import type { GddSectionKey } from "@/domain/models/constants";
import type { NonCanonicalBucket } from "@/domain/config/nonCanonicalBuckets";

export const CANONICAL_HEADING_SYNONYMS: Record<GddSectionKey, string[]> = {
  game_overview: [
    "overview",
    "game overview",
    "high concept",
    "vision",
    "summary",
    "tong quan",
    "tam nhin",
    "high concept tong quan",
  ],
  design_goals: [
    "design goals",
    "goals",
    "muc tieu thiet ke",
    "objective",
    "design intent",
    "north star",
  ],
  target_audience: [
    "target audience",
    "audience",
    "doi tuong nguoi choi",
    "nguoi choi muc tieu",
    "audience summary",
    "persona",
    "nguoi choi",
  ],
  core_pillars: ["pillars", "core pillars", "design pillars", "tru cot thiet ke", "pillar"],
  core_gameplay_loop: [
    "gameplay loop",
    "core loop",
    "vong lap choi",
    "loop choi",
    "moment to moment loop",
  ],
  controls: ["controls", "dieu khien", "input", "hud", "control scheme"],
  new_mechanics: [
    "mechanics",
    "new mechanics",
    "tinh nang moi",
    "co che",
    "features",
    "core mechanics systems",
    "physics rules",
  ],
  meta_layer: ["meta", "meta layer", "meta progression", "tien trinh meta", "progression"],
  monetization: ["monetization", "kiem tien", "iap", "battle pass"],
  aesthetic_direction: [
    "art direction",
    "aesthetic direction",
    "visual direction",
    "dinh huong my thuat",
  ],
  ftue: ["ftue", "tutorial", "onboarding", "tan thu", "huong dan dau game"],
  economy: ["economy", "resource flow", "nen kinh te", "currency", "reward flow"],
  live_ops: ["live ops", "events", "su kien", "van hanh live ops", "season", "kpi"],
  risks_assumptions: [
    "risks",
    "assumptions",
    "risks and assumptions",
    "rui ro",
    "gia dinh",
    "risk register",
    "production scope risks",
  ],
};

export const NON_CANONICAL_HEADING_SYNONYMS: Record<NonCanonicalBucket, string[]> = {
  document_purpose: ["muc dich tai lieu", "document purpose", "vai tro cua ban gdd nay", "purpose"],
  document_scope: ["pham vi", "document scope", "scope"],
  document_metadata: ["metadata", "thong tin tai lieu", "version history", "changelog"],
  current_direction_summary: ["current direction summary", "tong ket dinh huong hien tai", "direction summary"],
  target_audience_support: ["audience summary", "persona", "nguoi choi muc tieu"],
  audience_motivation: ["dong luc quay lai", "motivation", "retention triggers"],
  audience_pain_points: ["pain points", "pain point", "can tranh", "friction"],
  mechanics_systems: ["core mechanics systems", "cup system", "physics rules", "merge order fail state"],
  core_loop_support: ["moment to moment loop", "loop support", "core loop support"],
  tension_fail_state_logic: ["core tension model", "danger window", "grace window", "fail state"],
  level_content_framework: ["level design framework", "level content framework", "level framework"],
  queue_tuning: ["queue bias rules", "queue tuning"],
  numeric_tuning: ["numeric tuning framework", "numeric tuning", "balancing framework"],
  reward_payoff_design: ["reward payoff", "reward design", "payoff design"],
  progression_retention_support: ["progression retention", "retention support", "meta progression"],
  recovery_continue_design: ["continue recovery", "recovery design", "continue design"],
  tutorial_onboarding_support: ["tutorial support", "onboarding support", "ftue support"],
  economy_reward_flow: ["economy reward flow", "reward flow", "resource flow"],
  ui_hud_controls_support: ["ui hud controls", "hud", "controls support", "ui control"],
  production_scope_notes: ["production scope", "production notes", "delivery scope"],
  risks_assumptions_support: ["risk assumptions support", "risk notes", "assumption notes"],
  analytics_kpi_notes: ["self audit", "kpi", "metrics", "analytics notes"],
  appendix_notes: ["appendix", "phu luc"],
  supporting_notes: ["supporting notes", "ghi chu bo sung", "additional notes", "designer notes"],
  reference_notes: ["reference", "tai lieu tham chieu", "benchmark notes"],
  unknown_unmapped: [],
};
