export const NON_CANONICAL_BUCKETS = [
  "document_purpose",
  "document_scope",
  "document_metadata",
  "current_direction_summary",
  "target_audience_support",
  "audience_motivation",
  "audience_pain_points",
  "mechanics_systems",
  "core_loop_support",
  "tension_fail_state_logic",
  "level_content_framework",
  "queue_tuning",
  "numeric_tuning",
  "reward_payoff_design",
  "progression_retention_support",
  "recovery_continue_design",
  "tutorial_onboarding_support",
  "economy_reward_flow",
  "ui_hud_controls_support",
  "production_scope_notes",
  "risks_assumptions_support",
  "analytics_kpi_notes",
  "appendix_notes",
  "supporting_notes",
  "reference_notes",
  "unknown_unmapped",
] as const;

export type NonCanonicalBucket = (typeof NON_CANONICAL_BUCKETS)[number];
